FROM postgres:14.1-alpine

ENV POSTGRES_DB=db \
    POSTGRES_USER=usr \
    POSTGRES_PASSWORD=pwd

COPY ./10-CreateScheme.sql /docker-entrypoint-initdb.d/10-CreateScheme.sql
COPY ./20-InsertData.sql /docker-entrypoint-initdb.d/20-InsertData.sql