# Includes all other groups and hosts
all:
  # Variables under 'vars' apply to all hosts
  vars:
    # set user and ssh key for all hosts
    ansible_user: centos
    ansible_ssh_private_key_file: /mnt/wsl/id_rsa
  # 'children' is used to define child groups of the 'all' group
  children:
    # 'prod' is a child group of 'all'
    prod:
      # Define the host to connect to
      hosts: theo.gimond.takima.cloud