---
# tasks file for roles/app
- name: Run app
  docker_container:
    # Creates a Docker container named 'my-spring-boot'
    name: my-spring-boot
    image: tgimond/tp-devops-simple-api
    # Precises the environment variables for database connection
    env:
      DB_host: my-postgresdb
      DATABASE_USER: usr
      DATABASE_PASSWORD: pwd
      DATABASE_NAME: db
      DATABASE_PORT: "5432"
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3