---
# tasks file for roles/proxy
- name: Run proxy
  docker_container:
    name: my-http-container
    image: tgimond/tp-devops-httpd
    # Expose the container's port 80 to the host's port 80
    ports:
      - "80:80"
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3