# TODO: Choose a java JRE
FROM openjdk:11

# TODO:  Add the compiled java (aka bytecode, aka .class)
WORKDIR /app
COPY ./Main.class /app

# TODO: Run the Java with: “java Main” command.
CMD ["java","Main"]