name: Run Ansible Playbook

on:
  workflow_run:
    workflows: ["CI DevOps 2024"]
    types:
      - completed
    branches:
      - master

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH
      uses: webfactory/ssh-agent@v0.5.3  # Use the webfactory/ssh-agent action to set up SSH
      with:
        ssh-private-key: ${{ secrets.SSH_TOKEN }} 
        
    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H theo.gimond.takima.cloud >> ~/.ssh/known_hosts

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible