name: Deploy
on:
  workflow_run:
    workflows: ["CI devops 2024"]
    types:
      - completed
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/inventories/hosts
          extra-vars: '{"ansible_python_interpreter":"/usr/bin/python3"}'
          become: true
          become-user: root
          become-method: sudo