name: CI devops 2024
on:
  # Trigger the workflow on push or pull request to master or develop branches
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code from the current branch
      - uses: actions/checkout@v2.5.0

      # Setup JDK 17 for the job
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build and test the project with Maven
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: API/simple-api-student-main

  build-and-push-docker-image:
    # This job depends on the 'test-backend' job
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the backend Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          push: true
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      # Build and push the database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          push: true
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

      # Build and push the httpd Docker image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./httpd
          push: true
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest